// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynffsptntjvkumjzlfqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZmZzcHRudGp2a3VtanpsZnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzcyMTEsImV4cCI6MjA3MTM1MzIxMX0.tr7g-VNByVFgGaO_jYbQ8wjI_90qmIVPnFhFjdPrv6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});